// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchNote(arg1:string):Promise<Record<string, string>>;

export function PutNote(arg1:string,arg2:string):Promise<void>;

export function ShowDB():Promise<Record<string, string>>;
