// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchNote(arg1) {
  return window['go']['main']['App']['FetchNote'](arg1);
}

export function PutNote(arg1, arg2) {
  return window['go']['main']['App']['PutNote'](arg1, arg2);
}

export function ShowDB() {
  return window['go']['main']['App']['ShowDB']();
}
